### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by miikka** [open-telemetry/opentelemetry-lambda-extension#1082]
**Is your feature request related to a problem? Please describe.**

AWS Lambda now has [support for Python 3.12](https://aws.amazon.com/blogs/compute/python-3-12-runtime-now-available-in-aws-lambda/). It would be great to have Python 3.12 support in the Python + Collector Lambda layer, too.

**Describe the solution you'd like**

The included version of OpenTelemetry Python SDK should be bumped to [1.22.0](https://github.com/open-telemetry/opentelemetry-python/blob/main/CHANGELOG.md#version-1220043b0-2023-12-15) at least, since that version includes [this essential Python 3.12 compatibility fix](https://github.com/open-telemetry/opentelemetry-python/pull/3557).

Otherwise I'm not aware of big changes needed.

**Describe alternatives you've considered**

**Additional context**

**Comment by serkan-ozal** [comment]
@miikka @tylerbenson @rapphil Currently, OTEL Python SDK version `1.26.0` is used for OTEL Python later. So that version should be OK for Python `3.12` support.

But 
- we also need to specify supported runtimes in the published layer by `runtimes` parameter [here](https://github.com/open-telemetry/opentelemetry-lambda/blob/2087b126ae080573ba2944d2043245947b0e73a6/.github/workflows/release-layer-python.yml#L77)
- and add `3.12` to the Python version matrix [here](https://github.com/open-telemetry/opentelemetry-lambda/blob/2087b126ae080573ba2944d2043245947b0e73a6/.github/workflows/ci-python.yml#L29) as part of CI process

**Comment by rapphil** [comment]
@serkan-ozal makes sense. I don't see any blockers for not supporting Python 3.12.

**Comment by gliptak** [comment]
with #1576 merged, is there a tag/release process to be followed?

**Comment by tylerbenson** [comment]
I will try to do a release this week.

**Comment by fitz-vivodyne** [comment]
See https://github.com/open-telemetry/opentelemetry-lambda/releases/tag/layer-python%2F0.11.0
