### ISSUE TITLE
Node.js Layer using Depreated Exporter

### ISSUE THREAD

**Issue by astorm** [open-telemetry/opentelemetry-lambda-extension#183]
If I'm reading things correctly, the Node.js exporter that's used in the Node.js layer

https://github.com/open-telemetry/opentelemetry-lambda/blob/f6aadfd5932fa7e1e590936be153294645143694/nodejs/packages/layer/src/wrapper.ts#L39

is deprecated.  See https://cloud-native.slack.com/archives/C01NL1GRPQR/p1637779230143700

In addition to being deprecated, it does not appear that the deprecated `@opentelemetry/exporter-otlp-proto` allows users to export using OTLP over GRPC.  It only supports exporting over HTTP using `@opentelemetry/exporter-otlp-http`.

It would be great if this could be updated to use one of currently supported exporters _and_ if data could be exported via either GRPC and HTTP.  

(Not so great that I have time to take on the work, but great regardless ;))

**Comment by NathanielRN** [comment]
Hey @astorm! We've [been talking on Slack](https://cloud-native.slack.com/archives/CJFCJHG4Q/p1637781437031200) but I wanted to make sure this communication channel was answered too.

You're definitely right that `exporter-otlp-proto` is deprecated and we should work on building the NodeJS layer with `exporter-trace-otlp-proto` instead. We'll use this issue as a reminder to do that for the next release!

Regarding its use of HTTP by default, it seems that this is out of our control. Originally I thought we were moving to HTTP because of the architecture agonistic benefits, but I looked into the latest package from OTel JS `exporter-trace-otlp-proto` (i.e. the one that is to replace the now deprecated `exporter-otlp-proto`) and [the code indicates](https://github.com/open-telemetry/opentelemetry-js/blob/14afcc1f7bf3d9e33cdfc1aee8d83455eb7630ab/experimental/packages/opentelemetry-exporter-trace-otlp-proto/package.json#L71) that this package **uses the HTTP exporter by default**. So when we _do_ upgrade, it will still be an HTTP exporter. ~That’s an upstream decision, not one made by ADOT.~ (Sorry, this isn’t relevant to this repo, I got my repos mixed up!)

Hopefully this helps answer any doubts! Let me know if it does not!

**Comment by astorm** [comment]
I'm not too worried about the GRPC/HTTP thing, but since you mentioned it 

> that this package uses the HTTP exporter by default. So when we do upgrade, it will still be an HTTP exporter. That’s an upstream decision, not one made by ADOT.

I'm not sure I understand who "upstream" is here -- the ADOT layer is basically just a copy of what's in the [`open-telemetry/opentelemetry-lambda`](https://github.com/open-telemetry/opentelemetry-lambda) repo, right? And [`@opentelemetry/exporter-trace-otlp-proto`](https://github.com/open-telemetry/opentelemetry-js/tree/main/experimental/packages/opentelemetry-exporter-trace-otlp-proto) is also an OpenTelemetry project.  Since both projects are OpenTelemetry there's not an upstream relationship here —— either a PR to `@opentelemetry/exporter-trace-otlp-proto` to make the exporter configurable or direct use of _both_ `@opentelemetry/exporter-trace-otlp-grpc` and `@opentelemetry/exporter-trace-otlp-http` could give the lambda extension both HTTP and GRPC capabilities.  

Am I missing something?  Or as an amazon employee who works on ADOT do you view the OpenTelemetry project as a third party vendor whom you don't have influence over?  Or some other thing?

**Comment by NathanielRN** [comment]
Sorry for not being clear.

What I meant was that since _this_ repo uses [@opentelemetry/exporter-otlp-proto](https://www.npmjs.com/package/@opentelemetry/exporter-otlp-proto), the upgrade that would make sense would be to go to [@opentelemetry/exporter-trace-otlp-proto](https://www.npmjs.com/package/@opentelemetry/exporter-otlp-proto). I'm suggesting that we do that in this repo so that we can address the original issue in this thread that "Node.js Layer is using a Deprecated Exporter" since [that is what OpenTelemetry JS recommends](https://github.com/open-telemetry/opentelemetry-js/pull/2485).

Next, I noticed your description of the issue said in the body:

> It would be great if this could be updated to use one of currently supported exporters **and if data could be exported via either GRPC and HTTP.**

I'm just trying to point out that even if we _do_ upgrade to `@opentelemetry/exporter-trace-otlp-proto`, that won't change the fact that this package is using `http` as its implementation. We really appreciate user feedback because that can drive solutions like you mentioned which can lead to us including BOTH the HTTP and GRPC exporters in the Node.JS Lambda layer if that's what our users need, but that's a separate discussion in my opinion.
