### ISSUE TITLE
[Feature Request] .Net 6.0 support

### ISSUE THREAD

**Issue by dsharkou** [open-telemetry/opentelemetry-lambda-extension#234]
According to the [documentation](https://aws-otel.github.io/docs/getting-started/lambda/lambda-dotnet#instrumentation) I see .net 6.0 is not supported, while AWS Lambda supports .NET 6 runtime.

Could you please add layers, nuget package(s), etc. for .net6 to be able to integrate with AWS Lambda on this runtime?

**Comment by willarmiros** [comment]
Hi @dsharkou, have you tried following the AWS Lambda layer instructions with the .NET 6 runtime? The upstream OTel library should support .NET 6, and the layer will not be changed since it just involves running the collector in the Lambda runtime as an extension.

We are however working on a separate full-auto-instrumentation layer for .NET 6 functions, however there is no ETA at this time. We can use this issue to track that feature request.

**Comment by dsharkou** [comment]
@willarmiros Unfortunately nope, I haven't tried because saw the message .net 6 is not supported yet.
