### ISSUE TITLE
Clarify layer merge order

### ISSUE THREAD

**Issue by pranavmarla** [open-telemetry/opentelemetry-lambda-extension#749]
**Describe the bug**
The current documentation contains contradictory information regarding which lambda layer (auto-instrumentation vs collector) should be merged/added to the lambda first.

Specifically:
1. The [auto-instrumentation doc](https://opentelemetry.io/docs/faas/lambda-auto-instrument/) says you should add the collector layer first:
> See the [Collector Lambda layer guidance](https://opentelemetry.io/docs/faas/lambda-collector/) to add the layer to your application and configure the Collector. **We recommend you add this first.**

2. The [collector doc](https://opentelemetry.io/docs/faas/lambda-collector/) implies you should add the auto-instrumentation layer first:
> **Once you’ve instrumented your application** you should add the Collector Lambda layer to collect and submit your data to your chosen backend.

**What did you expect to see?**
- If the order in which the layers are merged into your lambda matters, clearly state what the recommended order is -- i.e. which layer we should add first: Auto-instrumentation or Collector?
- If the order does NOT matter, then clearly state that instead.

**Comment by tylerbenson** [comment]
@rapphil does the layer order matter?  I don't think it does.

**Comment by serkan-ozal** [comment]
@tylerbenson @rapphil I had some layer ordering issues in Thundra, so according to my experience, as long as layers have different paths under `/opt`, it is not a problem because there is no conflict/overlap. Otherwise, as far as I remember, last layer will be exported later and its content will override previous ones in case of conflict.

So, as far as I see, there is no possible conflict between collector layer and any instrumentation layer, layer order should not matter.
