### ISSUE TITLE
Incorrect Parent ID Assignment in root span for Node Lambda Functions

### ISSUE THREAD

**Issue by alingamn** [open-telemetry/opentelemetry-lambda-extension#992]
**Describe the bug**
In our application, we discovered an issue where the Node Lambda functions, which should ideally represent the root span, are being assigned a Parent ID. 

This issue occurs when we create a Lambda function, add a node js layer, and send an exit call to downstream. According to the expected behavior, the Parent ID in the span generated from Lambda function should be null.

**Steps to reproduce**
1. Create a Node js Lambda function.
2. Add OpenTelemetry node js layer [layer-nodejs/0.2.0](https://github.com/open-telemetry/opentelemetry-lambda/releases/tag/layer-nodejs%2F0.2.0) to the Lambda function.
3. Send an exit call to SQS.
4. Observe the Parent ID of the span generated for the lambda.

**What did you expect to see?**
The Parent ID for the root span, being from the Node lambda function, should be null.

**What did you see instead?**
Root span is being assigned a Parent ID instead of null.

**What version of collector/language SDK version did you use?**
Node.js 18.x for lambda
collector: v0.88.0

**What language layer did you use?**
Node JS

cc: @pavankrish123 @svrnm @noltak3

**Comment by tylerbenson** [comment]
Do you have "Active Tracing" enabled for your lambda?

**Comment by serkan-ozal** [comment]
@tylerbenson @alingamn 

I think there is a bug in the `opentelemetry-instrumentation-aws-lambda` package: https://github.com/open-telemetry/opentelemetry-js-contrib/blob/fa0139c048d21fabf94947f7313e44f6dbc1f79e/plugins/node/opentelemetry-instrumentation-aws-lambda/src/instrumentation.ts#L406

Regardless from `Active Tracing` is enabled or not, `_X_AMZN_TRACE_ID` is always there. But when `Active Tracing` is not enabled, its `Sampled` flag is `0`. So, when `Sampled` flag is `0`, parent context should be assumed as `null`.

However, the current implementation returns the extracted parent context from AWS XRay trace header if `Sampled` flag is `1` (this is OK), but doesn't return `null` if it is not sampled (since there is no return statement in else case, `_determineParent` call continues it execution and return parent extracted parent at the end of method even it is not sampled). I think, the correct code should be like this:
```js
      if (parent) {
        const spanContext = trace.getSpan(parent)?.spanContext();
        if (
          spanContext &&
          (spanContext.traceFlags & TraceFlags.SAMPLED) === TraceFlags.SAMPLED
        ) {
          // Trace header provided by Lambda only sampled if a sampled context was propagated from
          // an upstream cloud service such as S3, or the user is using X-Ray. In these cases, we
          // need to use it as the parent.
          return parent;
        } else {
          return null;
        }
      }
```

**Comment by serkan-ozal** [comment]
@tylerbenson @alingamn Created this issue in the `opentelemetry-js-contrib` repo: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/2416

**Comment by serkan-ozal** [comment]
Hi @tylerbenson @alingamn,

I have checked this issue again and seems that @tylerbenson is right. When AWS XRay "Active Tracing" is enabled, trace context is provided with sampled flag set. And there is no way to understand whether there is any upstream service or not by just looking at AWS XRay trace header. 

If you want to suppress this behavior, you can disable AWS context propagation by setting `OTEL_LAMBDA_DISABLE_AWS_CONTEXT_PROPAGATION` environment variable to `true`.

**Comment by tylerbenson** [comment]
Going forward you'll be able to control that using the global propagators instead.  Since we haven't heard back from the OP, I'm going to close the issue.  Feel free to reopen if needed.
